### ISSUE TITLE
Forums/Org Nav Subtask: Members page redesign

### ISSUE THREAD

**Issue by treasuretron** [spacebase/spacebasenz#105]
In GitLab by @StephenCataldo on Apr 18, 2018, 14:30

This redesigns the members-only group/id/members page, integrating into the new Org Profile nav system.

Google drive hosted mock up: https://drive.google.com/drive/folders/1Au8-BuYQNG_6oosgcBd23UVfZe0ruuKq

Steve, Kurt, and Rich spoke about that mockup and agree that we are implementing a three-state select UI with two buttons.  The states are pending, rejected, and accepted.  They are visually indicated as follows:

1. Pending: Red X UI element is **gray**, Green Check UI element is **gray**.
1. Accepted: Red X UI element is **gray**, Green Check UI element is **bright_green**.
1. Rejected: Red x UI element is **bright_red**, Green Check UI element is **gray**.

Traversing between the states can be done as follows:

* If you click a gray element, it becomes the bright element, and the other element becomes the gray element
* If you click a bright element, both elements become gray.

We agreed that a slider would be easier to cognitively accept for users iff the UI elements could be devised to properly indicate the state, and they could be fit into a UI on mobile.  That will be part of a future discussion.

**Member Management Test 1: The org owner can accept, reject, or leave pending** 

* [ ] Four users are pending.
* [ ] Org Owner accepts two, rejects one, leaves the third pending, clicks "go"
* [ ] Membership updated as expected (two accepted, one rejected, one pending)
* [ ] Emails go to accepted and rejected members, no email goes to pending member.

**Comment by treasuretron** [comment]
In GitLab by @StephenCataldo on Apr 18, 2018, 18:38

mentioned in commit 8b90e1fc26c65273a6bbe113bff9fce77cfbefd6

**Comment by treasuretron** [comment]
In GitLab by @StephenCataldo on Apr 18, 2018, 18:39

mentioned in commit 3745efd0cbab4c265b8b6e12f1af17ea3c2dd7fe

**Comment by treasuretron** [comment]
In GitLab by @richbodo on Apr 18, 2018, 22:59

changed title from **Forums/Org Nav Subtask: {-build a public & admin members page-}** to **Forums/Org Nav Subtask: {+Members page redesign+}**

**Comment by treasuretron** [comment]
In GitLab by @richbodo on Apr 18, 2018, 22:59

changed the description

**Comment by treasuretron** [comment]
In GitLab by @richbodo on Apr 18, 2018, 23:03

We don't need to take on any changes to the visibility of data in this issue.

We can simply redesign with data privacy AS-IS.  The current state of affairs is that org members are visible to other members of the org.  Org members are not visible to non-members.

In all cases where org members are not visible, the text "Join to view org members" should be listed.

It's just fine to have a blank page with that in the middle of it for people who are anonymous or site members but not members of that org.  

Later, after we have deployed and debugged this version, which is a lot of work, we can begin to design features that either hide or expose more data, and consider the ramifications of new data visibility experiments.

**Comment by treasuretron** [comment]
In GitLab by @richbodo on Apr 18, 2018, 23:06

removed milestone

**Comment by treasuretron** [comment]
In GitLab by @richbodo on Apr 26, 2018, 16:50

changed the description

**Comment by treasuretron** [comment]
In GitLab by @richbodo on Apr 26, 2018, 16:51

Hey @137px I wanted to capture my feedback on the new members page, and didn't see it documented anywhere else, so I put a few notes on the mockup in google drive.

**Comment by treasuretron** [comment]
In GitLab by @137px on May 8, 2018, 22:16

@StephenCataldo this is on PR-116. 

There are a couple things in the templates that need some logic (reject/accept buttons, admin badges) and then if you can output whatever checkboxes for accepting and rejecting in the "hidden" div on the pending view block template and then I will make the icons work with them.

**Comment by treasuretron** [comment]
In GitLab by @StephenCataldo on May 9, 2018, 12:19

marked this issue as related to #96

**Comment by treasuretron** [comment]
In GitLab by @richbodo on May 9, 2018, 12:23

changed the description

**Comment by treasuretron** [comment]
In GitLab by @richbodo on May 9, 2018, 16:00

changed the description

**Comment by treasuretron** [comment]
In GitLab by @richbodo on May 9, 2018, 16:00

I'm going to turn my comments on the google drive mockup into issues.

**Comment by treasuretron** [comment]
In GitLab by @richbodo on May 9, 2018, 16:05

changed the description

**Comment by treasuretron** [comment]
In GitLab by @richbodo on May 9, 2018, 16:06

changed the description

**Comment by treasuretron** [comment]
In GitLab by @richbodo on May 11, 2018, 23:52

changed the description

**Comment by treasuretron** [comment]
In GitLab by @richbodo on May 11, 2018, 23:53

@StephenCataldo @137px 

This is marked as in-progress.  Any blockers?

@Khiggins42 

Need you to do a couple things here:  First test pending member management on: https://us.platform.sh/projects/ensz4qdpjmziw/environments/pr-116

Second: 

Can you add the test in the description to our site regression test suite?  We need to test both the accept and reject emails, as well as the accuracy of accepting or rejecting in terms of updating the members list.

**Comment by treasuretron** [comment]
In GitLab by @StephenCataldo on May 17, 2018, 14:39

mentioned in commit 6244e2794d1562a2b75aad32a8ca5774c9097fbb

**Comment by treasuretron** [comment]
In GitLab by @StephenCataldo on May 17, 2018, 14:39

mentioned in commit cf255d0beefb72a58a65c9f8183e1488d903910b

**Comment by treasuretron** [comment]
In GitLab by @StephenCataldo on May 17, 2018, 14:44

mentioned in merge request !127

**Comment by treasuretron** [comment]
In GitLab by @StephenCataldo on May 17, 2018, 15:31

mentioned in commit 88c47bcb36f2c4753c2844fa4a8b97c5a5c3501c

**Comment by treasuretron** [comment]
In GitLab by @richbodo on May 18, 2018, 15:53

closed
