### ISSUE TITLE
Org-Level Blogs

### ISSUE THREAD

**Issue by treasuretron** [spacebase/spacebasenz#110]
In GitLab by @richbodo on Apr 18, 2018, 21:12

**User Stories - Phase One**

- [ ] As an Org Owner, I should be able to create a blog post that is published to a blog on my org pages
- [ ] As an Org Owner, I should be able to edit or delete any blog post in my Org
- [ ] As an Logged-out visitor, I should be able to view blog posts on Org pages

**Post Entity**
* Title
* Content
* Author
* Post Date

**Comment by treasuretron** [comment]
In GitLab by @aspiringweb on May 30, 2018, 20:58

removed milestone

**Comment by treasuretron** [comment]
In GitLab by @aspiringweb on May 30, 2018, 20:59

changed weight to **8**

**Comment by treasuretron** [comment]
In GitLab by @aspiringweb on May 30, 2018, 20:59

changed time estimate to 1w

**Comment by treasuretron** [comment]
In GitLab by @aspiringweb on May 30, 2018, 20:59

changed the description

**Comment by treasuretron** [comment]
In GitLab by @richbodo on Jul 9, 2018, 13:23

closed
