### ISSUE TITLE
Members can write blog posts for Orgs or for the Site-Blog

### ISSUE THREAD

**Issue by treasuretron** [spacebase/spacebasenz#111]
In GitLab by @richbodo on Apr 18, 2018, 21:32

I'm not sure this is the simplest way to do this.  I'm going for simplicity, but I think an approval process is ideal.  What I'm suggesting requires spacebase site members to have a section called "Blog Posts", which might be a block on their profile.  They would be able to open that, and write a Draft Blog Post for either a Group they are a member of, or the SpaceBase site-wide Blog.

- [ ] As a member of an Org, I should be able to write a Draft Blog Post for an Org
- [ ] As a member of an Org, I should be able to edit or delete a Draft Blog Post
- [ ] As an Org Owner, I should be able to accept or reject a Draft Blog Post from a member
- [ ] As an Org Owner, if I accept a draft blog post, it should be published to my org blog.  The user will get an email saying that it was accepted.
- [ ] As an Org Owner, if I reject a draft blog post, then I have to include a message saying why the post was rejected, and that blog post should stay in that users drafts.  The user will get an email saying that it was rejected.

**Comment by treasuretron** [comment]
In GitLab by @Khiggins42 on May 2, 2018, 17:57

@richbodo Couple of observations/questions:
*  who can approve a site-blog draft?
*  should ALL blog posts go through a draft/approval process for a consistent experience? 
*  should an org-member be able to delete their own published posts? Or would they need to request deletion?
*  will we keep archival records of deleted posts? (thinking liability stuff here) (maybe logs are enough?)
*  will we have a disclaimer relating to the content organizations create?

Reference [ACLs here](https://gitlab.com/spacebase/spacebase/wikis/ACLs%20by%20user%20type)

**Comment by treasuretron** [comment]
In GitLab by @richbodo on May 2, 2018, 18:36

Great questions.  I'll answer them here.

By way of generating context for these:  We need to discuss a UI for this.  This should probably be covered in a meeting, as ideating on options and contingencies go much more quickly in real-time meetings, and we'll probably come up with a prioritized MVP feature set faster that way.

- Q: who can approve a site-blog draft?

A: Anyone who is a drupal admin for the site.

- Q: should ALL blog posts go through a draft/approval process for a consistent experience?

A: Drupal admins do not need to go through the process at this time.  They can just create content and approve it - but they have to do it through the drupal admin back-end.  All other site members do need to propose a post for approval. 

- Q: should an org-member be able to delete their own published posts? Or would they need to request deletion?

A: No. Not in the MVP.  Once it's published, it's published.  If something needs an edit, the admin of the blog (site-owner, or org-owner) will need to edit it, or delete and repost.  We should consider this more as a future editing feature to tweak posts - it's unusual to have blog posts deleted - very common to edit and update them.

- Q: will we keep archival records of deleted posts? (thinking liability stuff here) (maybe logs are enough?)

A: Yes.  All original content - every bit on this site - with the exception of PII and trademarked logos - will be creative commons attribution-only licensed.  Every bit of content the spacebase staff creates will be the same.  Every line of code will be GPLv2.  Every other instance of the code that we affilliate with and allow to search in a global directory will have to license everything the same way.  That's the only way we can create an open directory for the space industry.

- Q: will we have a disclaimer relating to the content organizations create?

A: We will have T&C of the site, and a privacy policy, posted in another issue.  Everything will be covered there.  

- Q: What about GDPR and right to forget?  Doesn't that break the internet and every site like this that tries to put valuable science into the public domain?

A: Right to forget will be added on the same day we update the T&C.  You can ask us via email to pull the content you specify, and if it's yours, we'll pull it.  However, it will still be on the way-back machine and every other mirror not associated with us, and we're not going to try to visit those computers or their owners and enforce misguided GDPR policies for other people.

**Comment by treasuretron** [comment]
In GitLab by @aspiringweb on May 30, 2018, 20:58

removed milestone

**Comment by treasuretron** [comment]
In GitLab by @aspiringweb on May 30, 2018, 21:00

changed weight to **8**

**Comment by treasuretron** [comment]
In GitLab by @aspiringweb on May 30, 2018, 21:00

changed time estimate to 1w

**Comment by treasuretron** [comment]
In GitLab by @aspiringweb on Jul 12, 2018, 10:25

removed milestone

**Comment by treasuretron** [comment]
In GitLab by @richbodo on Oct 23, 2018, 15:34

closed
