### ISSUE TITLE
Time Zone should be present on calendar.  It's always NZ time, so we can just drop a text link in as a hack.

### ISSUE THREAD

**Issue by treasuretron** [spacebase/spacebasenz#112]
In GitLab by @richbodo on Apr 18, 2018, 21:50

We have solved all the other major calendaring issues, so I have repurposed this issue (106) to discuss one last issue:

We need an **indication** to users as to what time zone they are looking at, whenever they are looking at a calendar, be that year/month/week/day/or individual event view.

We don't need to calculate anything for the NZ Space Events Calendar, we just need to state the time zone so that people like me are reminded that this is not in their time zone.

**Comment by treasuretron** [comment]
In GitLab by @richbodo on Apr 24, 2018, 18:27

https://www.pr-95-w3tzjdq-ensz4qdpjmziw.us.platform.sh/ has the global and club specific calendar events. This can go live or we can wait a little longer. If it goes live we will just hide the events tab for now. There isn't much to complete this:
1) @McHoffa needs to hop in and make sure it looks the way he wants on the calendar view, node edit view, group node edit view, and event view. Pretty straight forward for him
2) For sidewide editing its good to go except for a pager issue
3) For org editing I have a final patch I need to complete and push to drupal.org so composer can download it. The links of the page or clicking on a day/week are not 100% but I will have that resolved today.

After that its basically tests and documentation. It's very simple and most of the work left is @McHoffa making it look good.

**Comment by treasuretron** [comment]
In GitLab by @richbodo on Apr 24, 2018, 18:27

assigned to @richbodo

**Comment by treasuretron** [comment]
In GitLab by @richbodo on Apr 30, 2018, 21:35

Sitewide Calendar Feature Requests (MVP):

* [x] Needs a title to identify it as the sitewide calendar at the top.  If we can edit the text in config that's the best.  Otherwise "Space Events in New Zealand" will do for now.
* [x] Week Mode needs clearer time designation on the left side (It's broken in a weird way - see attached.)  

Suggest form:

1:00PM

2:00PM

in that column, with a line break in between hours.

* [x] Week Mode needs nav to traverse to month mode.
* [ ] An indication of the Time Zone needs to be across the top (NZ time is the zone we're after, daylight time or not daylilght time needs to be indicated (NZ or NZDT) ).  We *probably* want to make that a thing on all calendars, as many calendars will span time zones, or list events in other time zones.
* [ ] An indication of the time zone, and AM/PM needs to be present on the event page for an event.  See attached.

![Screen_Shot_2018-04-30_at_6.32.09_PM](/uploads/69497430b1b0cd14371360ec94c7b820/Screen_Shot_2018-04-30_at_6.32.09_PM.png)

![Screen_Shot_2018-05-01_at_11.58.02_AM](/uploads/4ae6562654cdb876385c949568eed173/Screen_Shot_2018-05-01_at_11.58.02_AM.png)

**Comment by treasuretron** [comment]
In GitLab by @richbodo on May 12, 2018, 01:06

changed the description

**Comment by treasuretron** [comment]
In GitLab by @richbodo on May 12, 2018, 01:12

changed the description

**Comment by treasuretron** [comment]
In GitLab by @richbodo on May 12, 2018, 01:14

changed the description

**Comment by treasuretron** [comment]
In GitLab by @richbodo on May 12, 2018, 02:21

changed title from **SiteWide SpaceBase calendar** to **SiteWide SpaceBase calendar{+ - feature requests+}**

**Comment by treasuretron** [comment]
In GitLab by @richbodo on May 12, 2018, 02:21

changed the description

**Comment by treasuretron** [comment]
In GitLab by @Khiggins42 on May 22, 2018, 13:38

Observations:
1.  missing calendar nav when on year view
2.  need time zone indication on day and week view (edited)
3.  in week view, week 18 is indicated twice (Could be a function of what day of the week the week starts on.) (For reference, this site has facts about weeks-of-year, https://www.epochconverter.com/weeknumbers)

**Comment by treasuretron** [comment]
In GitLab by @richbodo on May 22, 2018, 19:03

changed title from **{-SiteWide SpaceBase calendar - feature requests-}** to **{+Time Zone should be present on calendar.  It's always NZ time, so we can just drop a text link in as a hack.+}**

**Comment by treasuretron** [comment]
In GitLab by @richbodo on May 22, 2018, 19:03

You guys knocked out the rest of the items here, for the most part.  The only thing left is the time zone.

**Comment by treasuretron** [comment]
In GitLab by @richbodo on May 23, 2018, 20:03

changed the description

**Comment by treasuretron** [comment]
In GitLab by @aspiringweb on May 30, 2018, 19:59

changed the description

**Comment by treasuretron** [comment]
In GitLab by @aspiringweb on May 30, 2018, 19:59

unassigned @richbodo

**Comment by treasuretron** [comment]
In GitLab by @aspiringweb on May 30, 2018, 21:10

changed time estimate to 2h

**Comment by treasuretron** [comment]
In GitLab by @aspiringweb on May 30, 2018, 21:10

changed weight to **1**

**Comment by treasuretron** [comment]
In GitLab by @aspiringweb on Jun 29, 2018, 14:02

mentioned in commit 891b6f559d5ba6620283ff6ad0d9dbc07ec48734

**Comment by treasuretron** [comment]
In GitLab by @aspiringweb on Jun 29, 2018, 14:02

mentioned in commit b56ad04dfdfd7d37f2a6b0a7b623e33a36a66b5a

**Comment by treasuretron** [comment]
In GitLab by @Khiggins42 on Jul 2, 2018, 14:42

Confirmed that on PR-176, time zone is now noted in monthly, weekly and daily calendars within each event.

**Comment by treasuretron** [comment]
In GitLab by @richbodo on Jul 2, 2018, 16:38

closed
