### ISSUE TITLE
Support Site Standard URL parsing (SSUP) across site for user URLentry

### ISSUE THREAD

**Issue by treasuretron** [spacebase/spacebasenz#121]
In GitLab by @richbodo on Apr 20, 2018, 19:42

This is the current policy for parsing and validating URLS from the user perspective.  It's correct as of the date Kurt tests it, and if it gets updated, we will want to update it across the site.  I don't want the spec to move underneath coders, or for the spec to be lost when this ticket is closed, so it's on a wiki page: https://gitlab.com/spacebase/spacebase/wikis/Site-Standard-URL-Parsing

It's fun to invent new acronyms an standards that only get used once.  But, it's more helpful when i point out code and discussions from others that might implement my crazy ideas: https://stackoverflow.com/questions/21870048/php-auto-correcting-urls

Here are some pages where we see a need for this:

- [ ] SSUP Supported on resources page on orgs
- [ ] SSUP Supported on org profile page
- [ ] SSUP Supported on user profile page

**Comment by treasuretron** [comment]
In GitLab by @richbodo on Apr 20, 2018, 19:45

changed title from **Support Site Standard URL parsing across site for user URLentry** to **Support Site Standard URL parsing {+(SSUP) +}across site for user URLentry**

**Comment by treasuretron** [comment]
In GitLab by @richbodo on Apr 20, 2018, 19:45

changed the description

**Comment by treasuretron** [comment]
In GitLab by @richbodo on Apr 23, 2018, 16:20

changed the description

**Comment by treasuretron** [comment]
In GitLab by @aspiringweb on Jul 12, 2018, 10:25

removed milestone
