### ISSUE TITLE
Create a devops group and add responsible parties

### ISSUE THREAD

**Issue by treasuretron** [spacebase/spacebasenz#192]
In GitLab by @richbodo on Jun 6, 2018, 16:19

There are a few system messages going out (currently to people who are no longer working on this project)  Nothing sensitive, but the messages could be useful, and we should have responsible people checking them

I.E: https://app.mailgun.com/app/logs/beta.spacebase.co/20180603044120.1.F92382184646E6B8%40beta.spacebase.co/history

So:

* [x] Scrub the config for mentions of michael@ixtlandesigns.com and replace with spacebaseadmin@spacebase.co
* [x] Create the spacebaseadmin@ group and add relevant parties
* [x] Point the current page monitoring to that group until we get more sophisticated stuff up.

**Comment by treasuretron** [comment]
In GitLab by @richbodo on Jun 6, 2018, 16:19

changed the description

**Comment by treasuretron** [comment]
In GitLab by @aspiringweb on Jul 12, 2018, 10:13

removed milestone

**Comment by treasuretron** [comment]
In GitLab by @aspiringweb on Jul 12, 2018, 10:14

changed weight to **4**

**Comment by treasuretron** [comment]
In GitLab by @aspiringweb on Jul 12, 2018, 10:14

changed time estimate to 1d

**Comment by treasuretron** [comment]
In GitLab by @aspiringweb on Jul 12, 2018, 10:14

unassigned @richbodo

**Comment by treasuretron** [comment]
In GitLab by @richbodo on Oct 23, 2018, 15:31

marked the task **Scrub the config for mentions of michael@ixtlandesigns.com and replace with spacebaseadmin@spacebase.co** as completed

**Comment by treasuretron** [comment]
In GitLab by @richbodo on Oct 23, 2018, 15:31

marked the task **Create the spacebaseadmin@ group and add relevant parties** as completed

**Comment by treasuretron** [comment]
In GitLab by @richbodo on Oct 23, 2018, 15:31

marked the task **Point the current page monitoring to that group until we get more sophisticated stuff up.** as completed

**Comment by treasuretron** [comment]
In GitLab by @richbodo on Oct 23, 2018, 15:31

closed
