### ISSUE TITLE
Search text field options - replace name and apply button wth description checkbox

### ISSUE THREAD

**Issue by treasuretron** [spacebase/spacebasenz#193]
In GitLab by @richbodo on Jun 7, 2018, 13:18

Documenting what we discussed in a separate issue:

* [x] Name is always searched, and description is optional, so name of org is always checked in UI
* [ ] Description checkbox triggers search as a button would
* [ ] Apply button can be removed

This method works for additional optional-text-fields as well, they each get implemented as the description does.

**Comment by treasuretron** [comment]
In GitLab by @richbodo on Jun 8, 2018, 17:09

marked the task **Name is always searched, and description is optional, so name of org is always checked in UI** as completed

**Comment by treasuretron** [comment]
In GitLab by @richbodo on Jun 8, 2018, 17:19

Got that first task knocked out, so MVP reached on this, but we're still looking to get the other two tasks implemented, so leaving this one open.

**Comment by treasuretron** [comment]
In GitLab by @aspiringweb on Jul 12, 2018, 10:00

changed time estimate to 2h

**Comment by treasuretron** [comment]
In GitLab by @aspiringweb on Jul 12, 2018, 10:00

changed weight to **1**

**Comment by treasuretron** [comment]
In GitLab by @aspiringweb on Aug 7, 2018, 12:06

mentioned in commit 6343a15cff68378c10dd3e5a302618d372b66425

**Comment by treasuretron** [comment]
In GitLab by @richbodo on Oct 23, 2018, 15:30

This was done.  The description checkbox doesn't save state, but that's reported elsewhere.

**Comment by treasuretron** [comment]
In GitLab by @richbodo on Oct 23, 2018, 15:30

closed
