### ISSUE TITLE
Captcha for contact/feedback forms

### ISSUE THREAD

**Issue by treasuretron** [spacebase/spacebasenz#224]
In GitLab by @richbodo on Jul 3, 2018, 17:15

* [x] Make a list of the contact forms that are on the site.
* [x] Document that list in the wiki
* [x] For any contact/feedback form that can be submitted that does not require a member login add a captcha like so: https://www.drupal.org/project/nocaptcha_recaptcha

**Comment by treasuretron** [comment]
In GitLab by @aspiringweb on Jul 3, 2018, 17:24

assigned to @Khiggins42

**Comment by treasuretron** [comment]
In GitLab by @aspiringweb on Jul 3, 2018, 17:25

@Khiggins42 please do the first two todo's on this issue and I will do the third with you.

**Comment by treasuretron** [comment]
In GitLab by @aspiringweb on Jul 12, 2018, 11:06

unassigned @aspiringweb

**Comment by treasuretron** [comment]
In GitLab by @aspiringweb on Jul 12, 2018, 11:06

changed weight to **2**

**Comment by treasuretron** [comment]
In GitLab by @aspiringweb on Jul 12, 2018, 11:09

changed time estimate to 4h

**Comment by treasuretron** [comment]
In GitLab by @Khiggins42 on Jul 13, 2018, 10:44

Wiki doc enumerating the two contact pages: https://gitlab.com/spacebase/spacebase/wikis/Contact-pages

**Comment by treasuretron** [comment]
In GitLab by @aspiringweb on Aug 7, 2018, 11:28

marked the task **Make a list of the contact forms that are on the site.** as completed

**Comment by treasuretron** [comment]
In GitLab by @aspiringweb on Aug 7, 2018, 11:28

marked the task **Document that list in the wiki** as completed

**Comment by treasuretron** [comment]
In GitLab by @aspiringweb on Aug 7, 2018, 11:28

marked the task **For any contact/feedback form that can be submitted that does not require a member login add a captcha like so: https://www.drupal.org/project/nocaptcha_recaptcha** as completed

**Comment by treasuretron** [comment]
In GitLab by @StephenCataldo on Oct 26, 2018, 00:20

marked this issue as related to #268

**Comment by treasuretron** [comment]
In GitLab by @StephenCataldo on Oct 26, 2018, 20:25

nocaptcha_recaptcha seems to have more than one error. Was it ever working — were we able to create accounts without errors once this was pushed live? I think I have a working version now and can make a patch... have to figure out how to test besides on my localhost before posting an untested patch.  @Khiggins42 @aspiringweb @richbodo

**Comment by treasuretron** [comment]
In GitLab by @richbodo on Oct 26, 2018, 22:00

@StephenCataldo I'm fairly certain that join functionality broke with the last prod push, and not before.  Nocaptcha was one of the many changes in that push.

Definitely patch and lets test.

To keep it clean, I suggest you make an estimate on #268 and close this issue and #268 when the prod push is done, making your estimate on that issue.

Given the severity of 268, we should be uber-aggressive with our prod pushes for this stuff.

**Comment by treasuretron** [comment]
In GitLab by @jayelless on Nov 6, 2018, 21:25

Deployment of the honeypot module has probably rendered this issue redundant, as the honeypot module will add the required trap field to each form automatically.

I recommend that this issue is closed.

**Comment by treasuretron** [comment]
In GitLab by @jayelless on Nov 6, 2018, 21:29

closed

**Comment by treasuretron** [comment]
In GitLab by @richbodo on Nov 7, 2018, 13:26

Thanks.  We will assume honeypot is working until proven otherwise.  The spammers that were stopped by the captchas are probably still out there so, at this stage of site development, it is fine to have them QA this.
