### ISSUE TITLE
Install and configure the metatag module

### ISSUE THREAD

**Issue by treasuretron** [spacebase/spacebasenz#232]
In GitLab by @aspiringweb on Jul 16, 2018, 01:15

We are going to use the metatag module to create the proper metatags required for seo, social cards, etc.

- [x] Install https://www.drupal.org/project/metatag module
- [x] Configure the sitewide defaults
- [x] Also the schema_metatag module.

Realistically the out of the box defaults should be good enough. You can look at the google, facebook and twitter tags for the sitewide default config and set them if they are not already set.

**Comment by treasuretron** [comment]
In GitLab by @aspiringweb on Jul 16, 2018, 01:18

marked this issue as related to #227

**Comment by treasuretron** [comment]
In GitLab by @aspiringweb on Jul 16, 2018, 01:20

marked this issue as related to #228

**Comment by treasuretron** [comment]
In GitLab by @aspiringweb on Jul 16, 2018, 01:21

marked this issue as related to #229

**Comment by treasuretron** [comment]
In GitLab by @aspiringweb on Jul 16, 2018, 01:23

marked this issue as related to #230

**Comment by treasuretron** [comment]
In GitLab by @aspiringweb on Jul 16, 2018, 01:24

marked this issue as related to #231

**Comment by treasuretron** [comment]
In GitLab by @aspiringweb on Jul 16, 2018, 01:26

marked this issue as related to #232

**Comment by treasuretron** [comment]
In GitLab by @aspiringweb on Jul 16, 2018, 01:28

marked this issue as related to #233

**Comment by treasuretron** [comment]
In GitLab by @StephenCataldo on Jul 16, 2018, 17:44

mentioned in merge request !193

**Comment by treasuretron** [comment]
In GitLab by @StephenCataldo on Jul 17, 2018, 18:05

mentioned in commit 6f3d04b6bbb31f714d98c95371292472f005df87

**Comment by treasuretron** [comment]
In GitLab by @StephenCataldo on Jul 17, 2018, 19:46

mentioned in commit 7b4a0e9dfc42a526ac8869e16c055e25bb474ac2

**Comment by treasuretron** [comment]
In GitLab by @StephenCataldo on Jul 17, 2018, 20:20

marked the task **Install https://www.drupal.org/project/metatag module** as completed

**Comment by treasuretron** [comment]
In GitLab by @StephenCataldo on Jul 17, 2018, 20:20

marked the task **Configure the sitewide defaults** as completed

**Comment by treasuretron** [comment]
In GitLab by @StephenCataldo on Jul 17, 2018, 20:27

mentioned in commit f16d39490a4b65bba07154416abd4c0de17e53b4

**Comment by treasuretron** [comment]
In GitLab by @StephenCataldo on Jul 17, 2018, 22:45

mentioned in commit 10619f4a414b0af3b492258e52a05fb7bba6f690

**Comment by treasuretron** [comment]
In GitLab by @StephenCataldo on Jul 17, 2018, 23:01

mentioned in commit b06fbf2ebc7d3f8a7395422556146ff9f60b96d6

**Comment by treasuretron** [comment]
In GitLab by @StephenCataldo on Jul 18, 2018, 12:46

mentioned in commit 83adb25e095a4e5e6c75d2432ce84bdbe102b4b7

**Comment by treasuretron** [comment]
In GitLab by @StephenCataldo on Jul 18, 2018, 13:05

My detailed worknotes including assumptions I made that I'd welcome other ideas; important at top and into the weeds:

@137px For images, best results use an image least 1200 x 630 pixels in size. Certainly a logo, and conceivably alternatives.

@richbodo Review the wording, especially the description for the home page. We need lots of wording at different lengths. I think it’s overboard except for key pieces of content, but we might start writing short blurbs that look good on google search returns.
Description: 320 characters or less
Google Plus wants less than 200 characters.
Abstract (less important) 150 characters or less

@richbodo I think we should also have unique meta tag description for the calendar, organizations. (People page, imo, main descrip ok?)

Related: aliases are not set for all content types (canonical url is set to node/x) 

I’m leaving the language blank because en-NZ — I’m not positive if this would confuse language searches? 

Google Plus and Facebook integration beyond Open Graph seems pointless for now.
*Twitter Card might be useful.
*Site Verification

Our existing data isn’t always a perfect fit: descriptions aren’t great summaries and I didn’t see a perfect solution. Placename doesn’t fit anything we have. I generally aim to put longer rather than shorter in these cases — don’t think this matters for interior content.

Event: I don’t yet see any date-related meta tags that aren’t focused on the content publication, turn on more options or look again. lat, long will be added later.

User location: I don't use lat, long since it's not specific.

**Comment by treasuretron** [comment]
In GitLab by @StephenCataldo on Jul 19, 2018, 14:09

changed the description

**Comment by treasuretron** [comment]
In GitLab by @StephenCataldo on Jul 19, 2018, 15:08

mentioned in commit 3a95235197796eb039558c17538c2c7a8d94ec84

**Comment by treasuretron** [comment]
In GitLab by @StephenCataldo on Jul 20, 2018, 17:31

changed the description

**Comment by treasuretron** [comment]
In GitLab by @StephenCataldo on Jul 31, 2018, 11:49

mentioned in commit 2c656e18fd000dec872fde9b6f0903a631c2e8fd

**Comment by treasuretron** [comment]
In GitLab by @StephenCataldo on Jul 31, 2018, 11:52

mentioned in merge request !206

**Comment by treasuretron** [comment]
In GitLab by @Khiggins42 on Jul 31, 2018, 14:02

@StephenCataldo 

Is this the desired image to be referenced in the metatags?
https://dev-54ta5gq-ensz4qdpjmziw.us.platform.sh/sites/default/files/inline-images/rocketlab-launch-platform.jpg


Organizations: missing some Opengraph tags
og:title og:type og:url og:description missing


Member: WARNING og:title og:url missing


News: WARNING og:url og:description missing


Video: WARNING og:url og:description missing
example page: https://dev-54ta5gq-ensz4qdpjmziw.us.platform.sh/node/89


Blog: WARNING og:url og:image og:description missing

**Comment by treasuretron** [comment]
In GitLab by @aspiringweb on Aug 2, 2018, 11:09

closed via merge request !206

**Comment by treasuretron** [comment]
In GitLab by @aspiringweb on Aug 2, 2018, 11:09

mentioned in commit 74e70af3d3b63eb8a426893e50a1ed77ef8e90a6
