### ISSUE TITLE
As a Group Admin, I should get notified when blog content is created in my group

### ISSUE THREAD

**Issue by treasuretron** [spacebase/spacebasenz#240]
In GitLab by @aspiringweb on Jul 16, 2018, 01:50

- [ ] Create email config in `spacebase_blogs/config/install/spacebase_blogs.mail.yml`
- [ ] Implement `spacebase_blogs_mail_edit_templates()`
- [ ] Implement `spacebase_blogs_node_insert()`

When blog content is created and it is part of a group, email all the admins of the group a simple message that it was created with a link to it. Not a lot of thought needs to go into this message since it can easily be changed later in code and via mail_edit module.

Add any reusable functionality for these admin notifications to `spacebase_core`

**Comment by treasuretron** [comment]
In GitLab by @aspiringweb on Jul 16, 2018, 01:52

marked this issue as related to #235

**Comment by treasuretron** [comment]
In GitLab by @StephenCataldo on Jul 30, 2018, 14:55

mentioned in merge request !203

**Comment by treasuretron** [comment]
In GitLab by @richbodo on Dec 11, 2018, 13:35

closed
