### ISSUE TITLE
As a Site Admin, I should get notified when blog content is created sitewide

### ISSUE THREAD

**Issue by treasuretron** [spacebase/spacebasenz#241]
In GitLab by @aspiringweb on Jul 16, 2018, 01:52

- [ ] Create email config in `spacebase_blogs/config/install/spacebase_blogs.mail.yml` and `spacebase_blogs.settings.yml`
- [x] Implement `spacebase_blogs_mail_edit_templates()`
- [x] Implement `spacebase_blogs_node_insert()`

When blog content is created and it is NOT part of a group, email a hardcoded list in a `spacebase_blogs.settings.yml` config variable a simple message that it was created with a link to it. Not a lot of thought needs to go into this message since it can easily be changed later in code and via mail_edit module.

Add any reusable functionality for these admin notifications to `spacebase_core`

**Comment by treasuretron** [comment]
In GitLab by @aspiringweb on Jul 16, 2018, 01:52

marked this issue as related to #234

**Comment by treasuretron** [comment]
In GitLab by @StephenCataldo on Jul 24, 2018, 13:13

marked the task **Implement `spacebase_blogs_mail_edit_templates()`** as completed

**Comment by treasuretron** [comment]
In GitLab by @StephenCataldo on Jul 24, 2018, 13:14

marked the task **Implement `spacebase_blogs_node_insert()`** as completed

**Comment by treasuretron** [comment]
In GitLab by @richbodo on Dec 11, 2018, 13:37

unassigned @StephenCataldo
