### ISSUE TITLE
As a Site Admin, I should get notified when video content is created sitewide

### ISSUE THREAD

**Issue by treasuretron** [spacebase/spacebasenz#243]
In GitLab by @aspiringweb on Jul 16, 2018, 01:58

- [ ] Create email config in `spacebase_videos/config/install/spacebase_videos.mail.yml` and `spacebase_videos.settings.yml`
- [ ] Implement `spacebase_videos_mail_edit_templates()`
- [ ] Implement `spacebase_videos_node_insert()`

When video content is created and it is NOT part of a group, email a hardcoded list in a `spacebase_videos.settings.yml` config variable a simple message that it was created with a link to it. Not a lot of thought needs to go into this message since it can easily be changed later in code and via mail_edit module.

Add any reusable functionality for these admin notifications to `spacebase_core`

**Comment by treasuretron** [comment]
In GitLab by @aspiringweb on Jul 16, 2018, 01:59

marked this issue as related to #236

**Comment by treasuretron** [comment]
In GitLab by @richbodo on Dec 11, 2018, 13:34

unassigned @StephenCataldo
