### ISSUE TITLE
As a Site Admin, I should get notified when event content is created sitewide

### ISSUE THREAD

**Issue by treasuretron** [spacebase/spacebasenz#245]
In GitLab by @aspiringweb on Jul 16, 2018, 02:01

- [ ] Create email config in `spacebase_events/config/install/spacebase_events.mail.yml` and `spacebase_events.settings.yml`
- [ ] Implement `spacebase_events_mail_edit_templates()`
- [ ] Implement `spacebase_events_node_insert()`

When event content is created and it is NOT part of a group, email a hardcoded list in a `spacebase_events.settings.yml` config variable a simple message that it was created with a link to it. Not a lot of thought needs to go into this message since it can easily be changed later in code and via mail_edit module.

Add any reusable functionality for these admin notifications to `spacebase_core`

**Comment by treasuretron** [comment]
In GitLab by @aspiringweb on Jul 16, 2018, 02:02

marked this issue as related to #238

**Comment by treasuretron** [comment]
In GitLab by @richbodo on Dec 11, 2018, 13:34

unassigned @StephenCataldo
