### ISSUE TITLE
As a Group Admin, I should get notified when news article content is created in my group

### ISSUE THREAD

**Issue by treasuretron** [spacebase/spacebasenz#246]
In GitLab by @aspiringweb on Jul 16, 2018, 02:03

- [ ] Create email config in `spacebase_news/config/install/spacebase_news.mail.yml`
- [ ] Implement `spacebase_news_mail_edit_templates()`
- [ ] Implement `spacebase_news_node_insert()`

When news article content is created and it is part of a group, email all the admins of the group a simple message that it was created with a link to it. Not a lot of thought needs to go into this message since it can easily be changed later in code and via mail_edit module.

Add any reusable functionality for these admin notifications to `spacebase_core`

**Comment by treasuretron** [comment]
In GitLab by @StephenCataldo on Jul 23, 2018, 18:16

mentioned in commit 2b12988344f66424d81a93b6bb0331685ac68a73

**Comment by treasuretron** [comment]
In GitLab by @StephenCataldo on Jul 23, 2018, 18:16

mentioned in commit 126cb9adc79cb6d6971362d46662efd041a247f1

**Comment by treasuretron** [comment]
In GitLab by @StephenCataldo on Jul 23, 2018, 18:16

mentioned in commit 28d643aa93d5e3a7debb0499dee3114feade3d80

**Comment by treasuretron** [comment]
In GitLab by @StephenCataldo on Jul 23, 2018, 18:20

mentioned in merge request !196

**Comment by treasuretron** [comment]
In GitLab by @StephenCataldo on Jul 24, 2018, 01:20

mentioned in commit 21329ec329ca43f4b97a3b7686a5c869aa6b77bf

**Comment by treasuretron** [comment]
In GitLab by @StephenCataldo on Jul 24, 2018, 02:02

mentioned in commit 5d66db7a32dd242d89787f846a4aafe6a43b4144

**Comment by treasuretron** [comment]
In GitLab by @StephenCataldo on Jul 24, 2018, 02:02

mentioned in commit bc488a69f3d2e98cef6230ddb22f68d09d1f4ae0

**Comment by treasuretron** [comment]
In GitLab by @StephenCataldo on Jul 24, 2018, 02:02

mentioned in commit 8c2c7f2f3e0f0ac8c39bb84157ca41f1624f741c

**Comment by treasuretron** [comment]
In GitLab by @StephenCataldo on Jul 24, 2018, 02:02

mentioned in commit 42fcd97ad898ca47aa6736df290a04bbc0873b5b

**Comment by treasuretron** [comment]
In GitLab by @StephenCataldo on Jul 24, 2018, 14:43

mentioned in commit 78943b9dc2991824567e9fc52c8376ae2506d359

**Comment by treasuretron** [comment]
In GitLab by @StephenCataldo on Jul 24, 2018, 16:50

mentioned in commit 7150baf4d5c7651ae4c00005021a40861188a8d9

**Comment by treasuretron** [comment]
In GitLab by @richbodo on Dec 11, 2018, 13:37

closed
