### ISSUE TITLE
As a Site Admin, I should get notified when news article content is created sitewide

### ISSUE THREAD

**Issue by treasuretron** [spacebase/spacebasenz#247]
In GitLab by @aspiringweb on Jul 16, 2018, 02:05

- [ ] Create email config in `spacebase_news/config/install/spacebase_news.mail.yml` and `spacebase_news.settings.yml`
- [ ] Implement `spacebase_news_mail_edit_templates()`
- [ ] Implement `spacebase_news_node_insert()`

When news article content is created and it is NOT part of a group, email a hardcoded list in a `spacebase_news.settings.yml` config variable a simple message that it was created with a link to it. Not a lot of thought needs to go into this message since it can easily be changed later in code and via mail_edit module.

Add any reusable functionality for these admin notifications to `spacebase_core`

**Comment by treasuretron** [comment]
In GitLab by @richbodo on Dec 11, 2018, 13:33

unassigned @StephenCataldo
