### ISSUE TITLE
As a Group Admin, I should get notified when resource content is created in my group

### ISSUE THREAD

**Issue by treasuretron** [spacebase/spacebasenz#248]
In GitLab by @aspiringweb on Jul 16, 2018, 02:06

- [ ] Create email config in `spacebase_resources/config/install/spacebase_resources.mail.yml`
- [x] Implement `spacebase_resources_mail_edit_templates()`
- [x] Implement `spacebase_resources_node_insert()`

When resource content is created and it is part of a group, email all the admins of the group a simple message that it was created with a link to it. Not a lot of thought needs to go into this message since it can easily be changed later in code and via mail_edit module.

Add any reusable functionality for these admin notifications to `spacebase_core`

**Comment by treasuretron** [comment]
In GitLab by @aspiringweb on Jul 16, 2018, 02:07

marked this issue as related to #243

**Comment by treasuretron** [comment]
In GitLab by @StephenCataldo on Jul 24, 2018, 22:05

marked the task **Implement `spacebase_resources_mail_edit_templates()`** as completed

**Comment by treasuretron** [comment]
In GitLab by @StephenCataldo on Jul 24, 2018, 22:05

marked the task **Implement `spacebase_resources_node_insert()`** as completed

**Comment by treasuretron** [comment]
In GitLab by @richbodo on Dec 11, 2018, 13:34

unassigned @StephenCataldo

**Comment by treasuretron** [comment]
In GitLab by @richbodo on Dec 13, 2018, 15:09

closed
