### ISSUE TITLE
As a Site Admin, I should get notified when resource content is created sitewide

### ISSUE THREAD

**Issue by treasuretron** [spacebase/spacebasenz#249]
In GitLab by @aspiringweb on Jul 16, 2018, 02:07

- [ ] Create email config in `spacebase_resources/config/install/spacebase_resources.mail.yml` and `spacebase_resources.settings.yml`
- [ ] Implement `spacebase_resources_mail_edit_templates()`
- [ ] Implement `spacebase_resources_node_insert()`

When resource content is created and it is NOT part of a group, email a hardcoded list in a `spacebase_resources.settings.yml` config variable a simple message that it was created with a link to it. Not a lot of thought needs to go into this message since it can easily be changed later in code and via mail_edit module.

Add any reusable functionality for these admin notifications to `spacebase_core`

**Comment by treasuretron** [comment]
In GitLab by @aspiringweb on Jul 16, 2018, 02:07

marked this issue as related to #242

**Comment by treasuretron** [comment]
In GitLab by @richbodo on Dec 11, 2018, 13:33

unassigned @StephenCataldo

**Comment by treasuretron** [comment]
In GitLab by @richbodo on Dec 13, 2018, 15:08

closed
