### ISSUE TITLE
As a Group Admin, I should get notified when project content is created in my group

### ISSUE THREAD

**Issue by treasuretron** [spacebase/spacebasenz#250]
In GitLab by @aspiringweb on Jul 16, 2018, 02:09

- [ ] Create email config in `spacebase_projects/config/install/spacebase_projects.mail.yml`
- [ ] Implement `spacebase_projects_mail_edit_templates()`
- [ ] Implement `spacebase_projects_node_insert()`

When project content is created and it is part of a group, email all the admins of the group a simple message that it was created with a link to it. Not a lot of thought needs to go into this message since it can easily be changed later in code and via mail_edit module.

Add any reusable functionality for these admin notifications to `spacebase_core`

**Comment by treasuretron** [comment]
In GitLab by @richbodo on Dec 11, 2018, 13:37

closed

**Comment by treasuretron** [comment]
In GitLab by @richbodo on Dec 11, 2018, 13:37

unassigned @StephenCataldo
