### ISSUE TITLE
As a Site Admin, I should get notified when project content is created sitewide

### ISSUE THREAD

**Issue by treasuretron** [spacebase/spacebasenz#251]
In GitLab by @aspiringweb on Jul 16, 2018, 02:10

- [ ] Create email config in `spacebase_projects/config/install/spacebase_projects.mail.yml` and `spacebase_projects.settings.yml`
- [ ] Implement `spacebase_projects_mail_edit_templates()`
- [ ] Implement `spacebase_projects_node_insert()`

When project content is created and it is NOT part of a group, email a hardcoded list in a `spacebase_projects.settings.yml` config variable a simple message that it was created with a link to it. Not a lot of thought needs to go into this message since it can easily be changed later in code and via mail_edit module.

Add any reusable functionality for these admin notifications to `spacebase_core`

**Comment by treasuretron** [comment]
In GitLab by @richbodo on Oct 23, 2018, 15:22

Closing - projects are handled differently.

Noting for posterity that:

We deferred use of the yml file.

System messaging is being specified here: https://gitlab.com/spacebase/spacebase/wikis/design-specs/email-notification-strategy

Projects are being defined here: https://gitlab.com/spacebase/spacebase/wikis/Design-Specs/Projects

**Comment by treasuretron** [comment]
In GitLab by @richbodo on Oct 23, 2018, 15:22

closed
