### ISSUE TITLE
Notifications: Daily Summaries

### ISSUE THREAD

**Issue by treasuretron** [spacebase/spacebasenz#258]
In GitLab by @StephenCataldo on Jul 30, 2018, 14:48

Tickets #234-245 are one workflow/qa process: building notifications for both Site Admins and Group Admins when new content is created, both immediate notices for single content and daily summaries.

- [x] For both Site and Group content, use node_insert() in the content's specific modules for immediate notices
- [x] spacebase_example_mail_edit_templates()
- [x] spacebase_example_node_insert()
- [x] figure out config: implement on live site `spacebase_resources/config/install/spacebase_resources.mail.yml` and `spacebase_resources.settings.yml`

- [x] Daily cron runs just after midnight in spacebase_core sends all yesterday's new content for each recipient.
- [x] Single template (within spacebase_core), insert a LIST of the summaries into it.
- [x] figure out config. Using yml at install is a setup for a more complex system later ... 

- [x] Alter the links for group resource content to the group, not the node alias. (Note for future: possibly that node alias should be to the group, if we never display the plain node. Assess for individual content types as more specs: where do a node's blogs display?)

**Comment by treasuretron** [comment]
In GitLab by @StephenCataldo on Jul 30, 2018, 14:48

changed the description

**Comment by treasuretron** [comment]
In GitLab by @StephenCataldo on Jul 30, 2018, 14:48

marked the task **For both Site and Group content, use node_insert() in the content's specific modules for immediate notices** as completed

**Comment by treasuretron** [comment]
In GitLab by @StephenCataldo on Jul 30, 2018, 14:48

marked the task **spacebase_example_mail_edit_templates()** as completed

**Comment by treasuretron** [comment]
In GitLab by @StephenCataldo on Jul 30, 2018, 14:48

marked the task **spacebase_example_node_insert()** as completed

**Comment by treasuretron** [comment]
In GitLab by @StephenCataldo on Jul 30, 2018, 14:51

mentioned in commit 5abe32abdbe86f58b66d847782de48f10a399467

**Comment by treasuretron** [comment]
In GitLab by @StephenCataldo on Jul 30, 2018, 14:51

mentioned in commit ce8decbe05023a0abdaad5957ebe408fb1221c9d

**Comment by treasuretron** [comment]
In GitLab by @StephenCataldo on Jul 30, 2018, 14:55

mentioned in merge request !203

**Comment by treasuretron** [comment]
In GitLab by @StephenCataldo on Jul 30, 2018, 16:00

mentioned in commit e545e08c1bb118deab195a3a606a4b3e38d2b0e6

**Comment by treasuretron** [comment]
In GitLab by @StephenCataldo on Jul 30, 2018, 16:43

mentioned in commit f9c421294d375eab25360092f41776444ef30ba3

**Comment by treasuretron** [comment]
In GitLab by @StephenCataldo on Jul 30, 2018, 17:10

mentioned in commit 4e9faceb2db15e9616385c1e01af775433486908

**Comment by treasuretron** [comment]
In GitLab by @StephenCataldo on Jul 30, 2018, 17:33

mentioned in commit e19f601b876536a937b758c86b56d393b0667c91

**Comment by treasuretron** [comment]
In GitLab by @StephenCataldo on Jul 30, 2018, 17:46

mentioned in commit 291f638c1c30bb7c005b2f1e7954dd920f3ec71c

**Comment by treasuretron** [comment]
In GitLab by @StephenCataldo on Jul 30, 2018, 17:52

QA warning: The default is not to get notices — be sure to change this before trying to QA.

**Comment by treasuretron** [comment]
In GitLab by @StephenCataldo on Jul 30, 2018, 23:06

mentioned in commit 8e2cf7591b1bc100fcfb3b8ce2d9395b708c429f

**Comment by treasuretron** [comment]
In GitLab by @StephenCataldo on Jul 31, 2018, 00:22

mentioned in commit ae8e86d383e51f2af4f32f46262d3ebf3c42e4e5

**Comment by treasuretron** [comment]
In GitLab by @StephenCataldo on Jul 31, 2018, 16:36

mentioned in commit 0d3a24db430f37a237e650b4a2bc76ce669c3522

**Comment by treasuretron** [comment]
In GitLab by @StephenCataldo on Jul 31, 2018, 17:20

mentioned in commit b47d73720cdba3852dd99a6557684d56f5ca9c37

**Comment by treasuretron** [comment]
In GitLab by @StephenCataldo on Jul 31, 2018, 19:00

mentioned in commit 9859f9583bd35c28ee1c54be69f7e21c6d9bb970

**Comment by treasuretron** [comment]
In GitLab by @StephenCataldo on Aug 1, 2018, 03:20

mentioned in commit f78b0c774435cf7918beebcb8f07b9f9eda34ae3

**Comment by treasuretron** [comment]
In GitLab by @StephenCataldo on Aug 1, 2018, 17:10

mentioned in commit e5cb848cf5f262a7ed36c9c7be0ebe630b219351

**Comment by treasuretron** [comment]
In GitLab by @StephenCataldo on Aug 1, 2018, 17:24

mentioned in commit 4850d270033586ecb3b7bdd2e1af12a9a7a1ef08

**Comment by treasuretron** [comment]
In GitLab by @StephenCataldo on Aug 1, 2018, 17:24

mentioned in commit 402d460384b215c2a3790228f157d313a2600fa4

**Comment by treasuretron** [comment]
In GitLab by @StephenCataldo on Aug 1, 2018, 17:26

mentioned in commit 030b0f78c08d87119fe89438d12eca6bc6958489

**Comment by treasuretron** [comment]
In GitLab by @StephenCataldo on Aug 1, 2018, 17:43

mentioned in commit e50883089e58ca06de1a570f137f07fdacbb6afd

**Comment by treasuretron** [comment]
In GitLab by @StephenCataldo on Aug 1, 2018, 18:15

mentioned in commit fd07ecf7e6d96dcfb9c2a71dd72432208ad5152d

**Comment by treasuretron** [comment]
In GitLab by @StephenCataldo on Aug 2, 2018, 02:33

mentioned in commit 7c6e661d90c91e90b6597b41716cdc14b8fcac7d

**Comment by treasuretron** [comment]
In GitLab by @StephenCataldo on Aug 2, 2018, 16:11

marked the task **figure out config: implement on live site `spacebase_resources/config/install/spacebase_resources.mail.yml` and `spacebase_resources.settings.yml`** as completed

**Comment by treasuretron** [comment]
In GitLab by @StephenCataldo on Aug 2, 2018, 16:11

marked the task **figure out config: implement on live site `spacebase_resources/config/install/spacebase_resources.mail.yml` and `spacebase_resources.settings.yml`** as incomplete

**Comment by treasuretron** [comment]
In GitLab by @StephenCataldo on Aug 2, 2018, 16:11

marked the task **Single template (within spacebase_core), insert a LIST of the summaries into it.** as completed

**Comment by treasuretron** [comment]
In GitLab by @StephenCataldo on Aug 2, 2018, 16:45

changed the description

**Comment by treasuretron** [comment]
In GitLab by @StephenCataldo on Aug 2, 2018, 19:21

mentioned in commit ba570ec50081a2ffd789256939e647db68a5b159

**Comment by treasuretron** [comment]
In GitLab by @StephenCataldo on Aug 2, 2018, 19:30

mentioned in commit f1df0d8f60a7229db70e31044867bcff70982482

**Comment by treasuretron** [comment]
In GitLab by @StephenCataldo on Aug 2, 2018, 19:38

mentioned in commit 524cccc6559b271cd7b2c26a43c819dc0614c223

**Comment by treasuretron** [comment]
In GitLab by @StephenCataldo on Aug 2, 2018, 19:50

mentioned in commit 74351e55473692097c65d3c7f17999745e900496

**Comment by treasuretron** [comment]
In GitLab by @StephenCataldo on Aug 2, 2018, 20:01

mentioned in commit 492ccf296729d168c6bb4c49c15f517890215882

**Comment by treasuretron** [comment]
In GitLab by @StephenCataldo on Aug 2, 2018, 20:34

mentioned in commit e957d347174f73a24c599a9affed2347f244990b

**Comment by treasuretron** [comment]
In GitLab by @StephenCataldo on Aug 2, 2018, 20:34

mentioned in commit cb4627f17f030eb9a072dddcb2d77bac2c2f6110

**Comment by treasuretron** [comment]
In GitLab by @StephenCataldo on Aug 2, 2018, 21:03

mentioned in commit 6cae62e6bc78b257fb85c07f9b9e51d450a89491

**Comment by treasuretron** [comment]
In GitLab by @StephenCataldo on Aug 2, 2018, 21:19

mentioned in commit 0357fcf6423e5b6b16135d51c545c12f01e1e80c

**Comment by treasuretron** [comment]
In GitLab by @StephenCataldo on Aug 2, 2018, 21:31

mentioned in commit d8c0aeb070a64ddc2e2736cfcb51e38f6711728f

**Comment by treasuretron** [comment]
In GitLab by @StephenCataldo on Aug 3, 2018, 02:27

mentioned in commit cf36d4f137262e7938e3b431325d090e8514aa4a

**Comment by treasuretron** [comment]
In GitLab by @StephenCataldo on Aug 3, 2018, 02:34

mentioned in commit 82021e43dbf18367b29963320732ba82f7560661

**Comment by treasuretron** [comment]
In GitLab by @StephenCataldo on Aug 3, 2018, 02:40

mentioned in commit 4a7ff255029af5ecb04cdb6051159923cfb7cff0

**Comment by treasuretron** [comment]
In GitLab by @StephenCataldo on Aug 3, 2018, 02:49

mentioned in commit 748efc9093194fccf4dc85e7e4437b0419ba0232

**Comment by treasuretron** [comment]
In GitLab by @StephenCataldo on Aug 3, 2018, 14:21

mentioned in commit 12b90211ba1333ae67ec03e4c9cdf4139a2c2c11

**Comment by treasuretron** [comment]
In GitLab by @StephenCataldo on Aug 3, 2018, 14:53

mentioned in commit 1e4fe048846e8c942ed0e4597ce1ee1041ef8079

**Comment by treasuretron** [comment]
In GitLab by @StephenCataldo on Aug 3, 2018, 15:03

mentioned in commit 91e92c499b2343e203b1a618ec442195091cef00

**Comment by treasuretron** [comment]
In GitLab by @StephenCataldo on Aug 3, 2018, 17:25

mentioned in commit 1af0e9fcd78017964a8e28eafd1b84d2c057c758

**Comment by treasuretron** [comment]
In GitLab by @StephenCataldo on Aug 3, 2018, 22:16

mentioned in commit cbb6346ac752f2a44f041060a75fb91d20612c6b

**Comment by treasuretron** [comment]
In GitLab by @StephenCataldo on Aug 3, 2018, 22:16

mentioned in commit 41b4b9405af6dab7d4555055aa245e59677faa7d

**Comment by treasuretron** [comment]
In GitLab by @StephenCataldo on Aug 4, 2018, 22:33

For the record / discussion / editing suggestions, here is a daily summary sent to me as both a Group Admin and Site Admin (thought that now goes to google groups unless the code is hand-edited):

Stephen Cataldo,

Daily summary of your new content follows:

New Site-Wide Content

Videos:

- Video Test 7am Aug 4 NZ, Aug 3 SU: https://pr-203-dxni36a-ensz4qdpjmziw.us.platform.sh/node/121

- Sat morning NZ video: https://pr-203-dxni36a-ensz4qdpjmziw.us.platform.sh/node/122

New Content in Your Groups

Resources:

- Sat morning NZ BAZCO resource should go immed to Stephen: https://pr-203-dxni36a-ensz4qdpjmziw.us.platform.sh/org/bazco

- Is queue system still working here or something bumped out?: https://pr-203-dxni36a-ensz4qdpjmziw.us.platform.sh/org/bazco

**Comment by treasuretron** [comment]
In GitLab by @StephenCataldo on Aug 4, 2018, 22:37

mentioned in commit 92472314f240050c5e2ed85001732790eec07aeb

**Comment by treasuretron** [comment]
In GitLab by @StephenCataldo on Aug 5, 2018, 02:37

marked the task **figure out config: implement on live site `spacebase_resources/config/install/spacebase_resources.mail.yml` and `spacebase_resources.settings.yml`** as completed

**Comment by treasuretron** [comment]
In GitLab by @StephenCataldo on Aug 5, 2018, 02:37

marked the task **Daily cron runs just after midnight in spacebase_core sends all yesterday's new content for each recipient.** as completed

**Comment by treasuretron** [comment]
In GitLab by @StephenCataldo on Aug 5, 2018, 02:37

marked the task **figure out config. Using yml at install is a setup for a more complex system later ... document shortcuts using drush[?] till more complex setup is built.** as completed

**Comment by treasuretron** [comment]
In GitLab by @StephenCataldo on Aug 5, 2018, 02:37

changed the description

**Comment by treasuretron** [comment]
In GitLab by @StephenCataldo on Aug 5, 2018, 02:38

marked the task **figure out config. Using yml at install is a setup for a more complex system later ...** as completed

**Comment by treasuretron** [comment]
In GitLab by @StephenCataldo on Aug 5, 2018, 02:38

marked the task **Alter the links for group resource content to the group, not the node alias. (Note for future: possibly that node alias should be to the group, if we never display the plain node. Assess for individual content types as more specs: where do a node's blogs display?)** as completed

**Comment by treasuretron** [comment]
In GitLab by @richbodo on Dec 11, 2018, 13:53

This was implememnted, but we still need to QA this on production.

**Comment by treasuretron** [comment]
In GitLab by @richbodo on Dec 11, 2018, 13:53

unassigned @StephenCataldo
