### ISSUE TITLE
Videos page last pieces

### ISSUE THREAD

**Issue by treasuretron** [spacebase/spacebasenz#261]
In GitLab by @richbodo on Aug 5, 2018, 02:17

In order of importance and expected implementation

**URL**: https://pr-211-vclkk5q-ensz4qdpjmziw.us.platform.sh/video

**Expected**:

In order of importance and expected implementation.

* [x] Videos icon on the grid menu traverses to videos page 
* [x] URL consistent in number with other pages, so https://pr-211-vclkk5q-ensz4qdpjmziw.us.platform.sh/videos with an "s" at the end. 
* [x] Author name present with link to author profile on video page below video after video title
* [ ] Add video button with consistent iconigraphy and verbage similar to the add blog or add event buttons on their respective pages - members only - adds unpublished. 

**Observed**: 

1-4 not present.

**Comment by treasuretron** [comment]
In GitLab by @richbodo on Aug 5, 2018, 02:23

assigned to @Khiggins42

**Comment by treasuretron** [comment]
In GitLab by @richbodo on Aug 5, 2018, 02:26

changed the description

**Comment by treasuretron** [comment]
In GitLab by @richbodo on Aug 5, 2018, 02:27

changed the description

**Comment by treasuretron** [comment]
In GitLab by @137px on Aug 5, 2018, 16:00

@richbodo done on 211, but menu item needs to be added once it's pushed to production

**Comment by treasuretron** [comment]
In GitLab by @richbodo on Aug 5, 2018, 17:43

changed the description

**Comment by treasuretron** [comment]
In GitLab by @richbodo on Aug 5, 2018, 18:00

As with news, we'll just test this a little more and push it.  Maybe we can add permissions to the videos page for site-members and disable the publish button for them on dev.

**Comment by treasuretron** [comment]
In GitLab by @richbodo on Nov 7, 2018, 13:49

assigned to @richbodo, @epaatdahlstrom , and @EricDahlstrom and unassigned @Khiggins42 and @137px

**Comment by treasuretron** [comment]
In GitLab by @richbodo on Nov 7, 2018, 13:52

@epaatdahlstrom  @EricDahlstrom Same deal with videos as with news.  It's time to QA by adding some to the site.  I can help at the end of the day.

Em, I don't know if you had a google doc on this but I know that we want video content from our youtube channel in here.  We should identify what we want up here and close this one when QA is done, creating any new issues needed to deal with new work to be done on this epic.

I will be talking with Megan tomorrow and we can easily manage Optimi or a fiverr hourly contractor to turn a spreadsheet or something else into content on a regular basis if there is a lot to do.

**Comment by treasuretron** [comment]
In GitLab by @richbodo on Nov 7, 2018, 17:46

marked this issue as related to #273
