### ISSUE TITLE
News page last bits

### ISSUE THREAD

**Issue by treasuretron** [spacebase/spacebasenz#262]
In GitLab by @richbodo on Aug 5, 2018, 02:25

Pretty much the same set of features that videos needs, and that blogs and events have

In order of importance and expected implementation

**URL**: https://pr-211-vclkk5q-ensz4qdpjmziw.us.platform.sh/news

**Expected**:

In order of importance and expected implementation

- [x] News icon on the grid menu traverses to news page
- [x] Author name present with link to author profile on video page below video after video title
- [ ] "Add news" button with consistent iconigraphy and verbage similar to the add blog or add event buttons on their respective pages - members only - adds unpublished.  

**Observed**: 

1-3 not present.

**Comment by treasuretron** [comment]
In GitLab by @137px on Aug 5, 2018, 15:59

@richbodo done on 211, but menu item needs to be added once it's pushed to production

**Comment by treasuretron** [comment]
In GitLab by @richbodo on Aug 5, 2018, 17:50

changed the description

**Comment by treasuretron** [comment]
In GitLab by @richbodo on Aug 5, 2018, 17:57

This can be complete with one exception - site members cannot yet add news.  Only the admin can.

I envisioned that site-members could contribute news items but not publish in the MVP.

However, I think I'll call this an MVP and close it out after we test on dev.

**Comment by treasuretron** [comment]
In GitLab by @richbodo on Aug 5, 2018, 17:58

@137px into what directory do the icons get checked in?  I can grab them and add the menu items on prod.

**Comment by treasuretron** [comment]
In GitLab by @137px on Aug 5, 2018, 18:00

to add the menu items, just add the links under Structure > Menus > Main menu, and under Attributes, add a class nav-news, nav-blog, etc

**Comment by treasuretron** [comment]
In GitLab by @aspiringweb on Aug 7, 2018, 12:39

changed the description

**Comment by treasuretron** [comment]
In GitLab by @richbodo on Nov 7, 2018, 13:47

assigned to @richbodo, @epaatdahlstrom , and @EricDahlstrom and unassigned @Khiggins42 and @137px

**Comment by treasuretron** [comment]
In GitLab by @richbodo on Nov 7, 2018, 13:49

@epaatdahlstrom  @EricDahlstrom It's time to QA news by adding some to the site.  I can help at the end of the day.

Em, I think you had a link to a google doc with news content that you wanted added.  Don't have that immediately handy.  We should drop that in here and close this one when QA is done, creating any new issues needed to deal with new work to be done on this epic.

**Comment by treasuretron** [comment]
In GitLab by @richbodo on Nov 7, 2018, 17:46

marked this issue as related to #273
