### ISSUE TITLE
Security Update and MR208 push

### ISSUE THREAD

**Issue by treasuretron** [spacebase/spacebasenz#268]
In GitLab by @richbodo on Aug 29, 2018, 17:05

Apply security updates to MR208, merge to prod and dev.  We have performed QA on MR 208 well enough that the basic functionality is proven out.

* [ ] Apply security updates that need to be deployed.
* [x] Merge security updates and MR208 onto prod.
* [ ] For good measure, merge master to dev.

https://gitlab.com/spacebase/spacebase/merge_requests/208

**Comment by treasuretron** [comment]
In GitLab by @richbodo on Aug 30, 2018, 11:55

assigned to @aspiringweb

**Comment by treasuretron** [comment]
In GitLab by @richbodo on Aug 30, 2018, 11:55

@aspiringweb Can you estimate this?

**Comment by treasuretron** [comment]
In GitLab by @richbodo on Aug 30, 2018, 16:36

changed the description

**Comment by treasuretron** [comment]
In GitLab by @aspiringweb on Sep 18, 2018, 18:02

changed time estimate to 2h

**Comment by treasuretron** [comment]
In GitLab by @aspiringweb on Sep 20, 2018, 19:24

mentioned in commit 2be2d1c58772a9b8a27b14748090b6cd253b432f

**Comment by treasuretron** [comment]
In GitLab by @richbodo on Sep 27, 2018, 20:05

marked the task **Merge security updates and MR208 onto prod.** as completed

**Comment by treasuretron** [comment]
In GitLab by @richbodo on Nov 19, 2018, 19:44

changed weight to **4**

**Comment by treasuretron** [comment]
In GitLab by @richbodo on Nov 19, 2018, 19:49

closed
