### ISSUE TITLE
New Relic Config

### ISSUE THREAD

**Issue by treasuretron** [spacebase/spacebasenz#30]
In GitLab by @richbodo on Jan 26, 2018, 03:48

TODO as per: https://docs.platform.sh/golive/steps.html

* [x] Add domains beta.spacebase.co, and spacebase.co
* [ ] Specify HTTPS routes in routes.yaml (if not there)
* [ ] Add a low disk warning via both email and slack

Note, as of this writing:

Our URL is: master-7rqtwti-ensz4qdpjmziw.us.platform.sh
Our IP is: 54.210.49.244

Also TODO, as per: https://docs.platform.sh/administration/integrations/new-relic.html

* [x] Add a NewRelic license key (6619c8427e65cff4c1ee3b6e40e182e6f2b014cb)
* [ ] Update .platform.app.yaml and push (to the right .platform.app.yaml)

More NewRelic configuration will likely be on other tickets

**Comment by treasuretron** [comment]
In GitLab by @richbodo on Jan 26, 2018, 03:48

marked the task **Add a NewRelic license key (6619c8427e65cff4c1ee3b6e40e182e6f2b014cb)** as completed

**Comment by treasuretron** [comment]
In GitLab by @richbodo on Jan 30, 2018, 05:07

marked the task **Add domains beta.spacebase.co, and spacebase.co** as completed

**Comment by treasuretron** [comment]
In GitLab by @richbodo on Feb 21, 2018, 18:28

assigned to @richbodo

**Comment by treasuretron** [comment]
In GitLab by @richbodo on Mar 6, 2018, 21:39

changed title from **{-Platform.sh GoLive Configuration-}** to **{+New Relic Config+}**

**Comment by treasuretron** [comment]
In GitLab by @richbodo on Mar 26, 2018, 16:10

unassigned @richbodo

**Comment by treasuretron** [comment]
In GitLab by @richbodo on Apr 17, 2018, 19:48

removed milestone

**Comment by treasuretron** [comment]
In GitLab by @aspiringweb on Jul 12, 2018, 10:13

removed milestone

**Comment by treasuretron** [comment]
In GitLab by @thomasmurphy on Mar 1, 2019, 00:17

mentioned in merge request !276
