### ISSUE TITLE
339 - Space Challenge Launch Requirements

### ISSUE THREAD

**Issue by treasuretron** [spacebase/spacebasenz#345]
In GitLab by @thomasmurphy on Mar 11, 2019, 20:25

This is a meta ticket to link to required tasks and list non-ticket tasks.
* [x] Search Results #340 
* [x] Grid nav #341
* [x] Design and front-end repair work #332 , #333 , #334 , #335 , #337 , #338 
* [ ] Private Project Discussion Threads #342 #321
* [ ] Private Project Resources #343
* [x] change permissions on project creation to only allow editors and admins #353
* [x] make a manual block of all space-challenge projects to display on arbitrary paths. #354

**Comment by treasuretron** [comment]
In GitLab by @thomasmurphy on Mar 11, 2019, 20:25

changed title from **Space Challenge Launch Requirements** to **{+339 - +}Space Challenge Launch Requirements**

**Comment by treasuretron** [comment]
In GitLab by @richbodo on Mar 11, 2019, 20:39

changed the description

**Comment by treasuretron** [comment]
In GitLab by @richbodo on Mar 11, 2019, 21:31

changed the description

**Comment by treasuretron** [comment]
In GitLab by @thomasmurphy on Mar 12, 2019, 21:52

changed the description

**Comment by treasuretron** [comment]
In GitLab by @richbodo on Mar 12, 2019, 21:58

changed the description

**Comment by treasuretron** [comment]
In GitLab by @thomasmurphy on Mar 12, 2019, 22:37

changed the description

**Comment by treasuretron** [comment]
In GitLab by @thomasmurphy on Mar 12, 2019, 22:54

changed the description

**Comment by treasuretron** [comment]
In GitLab by @richbodo on Mar 18, 2019, 00:47

closed

**Comment by treasuretron** [comment]
In GitLab by @thomasmurphy on Mar 18, 2019, 00:52

@richbodo this is the main ticket I'm working off as agreed when we had the last meeting, what's the reason for closing it?

**Comment by treasuretron** [comment]
In GitLab by @thomasmurphy on Mar 21, 2019, 16:46

reopened

**Comment by treasuretron** [comment]
In GitLab by @thomasmurphy on Mar 21, 2019, 16:55

changed the description

**Comment by treasuretron** [comment]
In GitLab by @thomasmurphy on Mar 21, 2019, 16:56

changed the description

**Comment by treasuretron** [comment]
In GitLab by @thomasmurphy on Mar 21, 2019, 16:56

changed the description

**Comment by treasuretron** [comment]
In GitLab by @thomasmurphy on Mar 21, 2019, 17:01

marked the task **Search Results #340** as completed

**Comment by treasuretron** [comment]
In GitLab by @thomasmurphy on Mar 21, 2019, 17:01

marked the task **change permissions on project creation to only allow editors and admins #353** as completed

**Comment by treasuretron** [comment]
In GitLab by @richbodo on Mar 21, 2019, 19:12

Hey Thomas, the reason for closing it was because I had put all of these tickets into a milestone which I had hoped we would use together, but I think we've covered this well and we are clear that you can keep using this and any other methods you need.

**Comment by treasuretron** [comment]
In GitLab by @thomasmurphy on Mar 21, 2019, 22:50

marked the task **Grid nav #341** as completed

**Comment by treasuretron** [comment]
In GitLab by @thomasmurphy on Mar 24, 2019, 20:28

marked the task **make a manual block of all space-challenge projects to display on arbitrary paths. #354** as completed

**Comment by treasuretron** [comment]
In GitLab by @thomasmurphy on Mar 26, 2019, 21:39

mentioned in merge request !283

**Comment by treasuretron** [comment]
In GitLab by @thomasmurphy on Mar 27, 2019, 00:55

@richbodo can you have a look at https://pr-283-b55kqtq-ensz4qdpjmziw.us.platform.sh and tell us what you think? 

My preference is to merge this into dev to 
1) make the dev database more useful to download for further development and 
2) allow some more complex content to be entered on master to allow better theming

I think we're close.

**Comment by treasuretron** [comment]
In GitLab by @thomasmurphy on Mar 27, 2019, 22:09

marked the task **Design and front-end repair work #332 , #333 , #334 , #335 , #337 , #338** as completed

**Comment by treasuretron** [comment]
In GitLab by @thomasmurphy on Mar 27, 2019, 22:20

closed via merge request !283

**Comment by treasuretron** [comment]
In GitLab by @thomasmurphy on Mar 27, 2019, 22:20

mentioned in commit 85b6ed2003bf21d0ecbfa80942a33dc799849084

**Comment by treasuretron** [comment]
In GitLab by @richbodo on Mar 28, 2019, 16:30

I get a 404 on that environment, @thomasmurphy
