### ISSUE TITLE
New Dev Documentation Testing

### ISSUE THREAD

**Issue by treasuretron** [spacebase/spacebasenz#367]
In GitLab by @richbodo on Apr 4, 2019, 17:40

Test the following docs:

* [ ] https://gitlab.com/spacebase/spacebase/wikis/Local-environment-setup
* [ ] https://gitlab.com/spacebase/spacebase/wikis/Branch-Switching
* [ ] https://gitlab.com/spacebase/spacebase/wikis/Development#merging-and-pushing-to-dev-and-prodmaster
* [ ] https://gitlab.com/spacebase/spacebase/wikis/Development/Behat

**Comment by treasuretron** [comment]
In GitLab by @richbodo on Apr 4, 2019, 17:40

changed due date to April 13, 2019
