### ISSUE TITLE
Prod push/rollback docs

### ISSUE THREAD

**Issue by treasuretron** [spacebase/spacebasenz#60]
In GitLab by @richbodo on Feb 22, 2018, 20:56

* [ ]  Fix this production push tutorial:

https://gitlab.com/spacebase/spacebase/wikis/Development#merging-and-pushing-to-dev-and-prodmaster

* [ ]  Walk through that to get signoff by making a small change and pushing according to the new instructions.

* [ ]  Take a quick browse through the wiki to see if we have any orphan docs on this topic and integrate, remove, or cross link docs as needed to make the docs consistent here.
 
* [ ] Optional: document code rollback (not data migration or repair) with either a git rebase or another method

* [ ] Optional: document using platforms "snapshot" system to roll back to a snapshot.

**Comment by treasuretron** [comment]
In GitLab by @richbodo on Mar 24, 2018, 17:12

Matt, I have some rough notes on this.  They are here right now:

https://gitlab.com/spacebase/spacebase/wikis/Development#merging-and-pushing-to-dev-and-prodmaster

It could be that I am not finding the right doc, but we should flatten any duplicate attempts to doc prod push/rollback into one doc.

You're the best person to fix these docs, so I would love to get your help with this.

**Comment by treasuretron** [comment]
In GitLab by @richbodo on Mar 28, 2018, 17:53

assigned to @StephenCataldo

**Comment by treasuretron** [comment]
In GitLab by @richbodo on Apr 2, 2018, 19:22

assigned to @Khiggins42

**Comment by treasuretron** [comment]
In GitLab by @richbodo on Apr 17, 2018, 19:50

removed milestone

**Comment by treasuretron** [comment]
In GitLab by @aspiringweb on May 30, 2018, 21:18

changed time estimate to 2h

**Comment by treasuretron** [comment]
In GitLab by @aspiringweb on May 30, 2018, 21:18

changed weight to **3**

**Comment by treasuretron** [comment]
In GitLab by @aspiringweb on May 31, 2018, 12:53

removed milestone

**Comment by treasuretron** [comment]
In GitLab by @richbodo on Jun 5, 2018, 17:52

assigned to @richbodo

**Comment by treasuretron** [comment]
In GitLab by @aspiringweb on Jul 12, 2018, 10:17

removed milestone

**Comment by treasuretron** [comment]
In GitLab by @richbodo on Aug 29, 2018, 16:13

unassigned @Khiggins42, @aspiringweb, @richbodo, and @StephenCataldo

**Comment by treasuretron** [comment]
In GitLab by @richbodo on Aug 29, 2018, 16:20

changed the description

**Comment by treasuretron** [comment]
In GitLab by @richbodo on Aug 30, 2018, 16:25

removed time estimate

**Comment by treasuretron** [comment]
In GitLab by @aspiringweb on Sep 18, 2018, 18:05

changed time estimate to 4h

**Comment by treasuretron** [comment]
In GitLab by @richbodo on Sep 21, 2018, 19:38

assigned to @aspiringweb

**Comment by treasuretron** [comment]
In GitLab by @jayelless on Nov 28, 2018, 18:28

I think that some updates are required.  In particular, it is unwise to use the command "lando composer update" as this will update any Drupal modules, core, and vendor libraries that have more recent releases available.  It is not advisable to perform a blanket update.

A better policy is to use the command "lando composer outdated --direct" to generate a list of modules etc that could be updated if required.  Update any that are important and leave the rest alone.

If you only want to ensure that your codebase is matching the prod or dev environments, then the command to use is "lando composer install" which will just install the versions specified in the composer.lock file.

For this reason, action when resolving merge conflicts should ensure that the correct content in the composer.lock file is committed at the end of the process.

If you have the correct version of the modules and vendor libraries installed, then the command "lando composer update --lock" will just update the lock file to fix any date or hash issues.  It would be useful to run this command at the completion of a merge that had merge conflicts in the composer.lock file to ensure it is correct.

**Comment by treasuretron** [comment]
In GitLab by @jayelless on Nov 29, 2018, 17:14

assigned to @jayelless and unassigned @aspiringweb

**Comment by treasuretron** [comment]
In GitLab by @jayelless on Dec 5, 2018, 19:20

The wiki page https://gitlab.com/spacebase/spacebase/wikis/Development has been updated with a section on pushing to dev and prod (master) which also includes rollback instructions.

**Comment by treasuretron** [comment]
In GitLab by @jayelless on Dec 5, 2018, 19:20

closed
