### ISSUE TITLE
Events for spacebase members

### ISSUE THREAD

**Issue by treasuretron** [spacebase/spacebasenz#72]
In GitLab by @aspiringweb on Mar 7, 2018, 19:14

Unlike blogs, events are rarely drafted again and again, and no one really wants credit for them, or a list of the ones they have created on their profile.  So this is a bit simpler than blogs in that way.

**User Stories**

**Event Entity**
* Title
* Description
* Start
* End
* Location
* Author
* Website
* Registration URL
- [ ]  As a SpaceBase site member, I should be able to create unpublished events for any group calendar that I am  a member of, or for the spacebase site-wide calendar.
- [ ]  As an Org Owner, I should be able to publish events that have been created by members of my Org, or reject them.
- [ ]  As an Org Owner, if I reject an event, I should have to state a reason, and an email should go out to that user with that reason (I suppose leaving the text field blank is o.k.).
- [ ]  As an Org Owner, if I accept an event, that calendar event should appear on my org calendar, and the person who suggested the event should get an email saying that the event has been accepted.
- [ ]  As an Org Owner, I should be able to edit or delete an event on my org-level calendar.
- [ ]  As a Visitor, I should be able to search for events on the site
- [ ]  As a Visitor, I should be able to search for events in a group
- [ ]  As a Visitor, I should be able to add a spacebase group calendar, or the spacebase sitewide calendar, to my google calendar (probably via a link to an ics file).
- [ ]  As a Visitor, I should be able to see events in a list view and calendar view

**Comment by treasuretron** [comment]
In GitLab by @richbodo on Mar 28, 2018, 17:41

marked this issue as related to #76

**Comment by treasuretron** [comment]
In GitLab by @richbodo on Apr 18, 2018, 21:43

changed title from **{-Calendars & Event-}s** to **{+Events for spacebase member+}s**

**Comment by treasuretron** [comment]
In GitLab by @richbodo on Apr 18, 2018, 21:43

changed the description

**Comment by treasuretron** [comment]
In GitLab by @aspiringweb on May 30, 2018, 19:59

changed the description

**Comment by treasuretron** [comment]
In GitLab by @aspiringweb on Jul 12, 2018, 10:25

removed milestone

**Comment by treasuretron** [comment]
In GitLab by @richbodo on Dec 11, 2018, 13:41

closed
