### ISSUE TITLE
Only a user can edit his own profile - behat test

### ISSUE THREAD

**Issue by treasuretron** [spacebase/spacebasenz#98]
In GitLab by @richbodo on Apr 17, 2018, 20:18

* [x] Log in as a user we have recently created
* [x] View profile
* [ ] Edit profile
* [ ] Anon user cannot edit, but can view.
* [x] Other logged in users cannot edit, but can view.
* [x] Login with username that has special characters

**Comment by treasuretron** [comment]
In GitLab by @aspiringweb on Jul 12, 2018, 10:04

changed the description

**Comment by treasuretron** [comment]
In GitLab by @aspiringweb on Jul 12, 2018, 10:04

changed the description

**Comment by treasuretron** [comment]
In GitLab by @aspiringweb on Jul 12, 2018, 10:07

changed weight to **6**

**Comment by treasuretron** [comment]
In GitLab by @Khiggins42 on Jul 12, 2018, 13:39

* [x] Log in as a user we have recently created

done

* [x] View profile

done

* [ ] Edit profile

not done; troubleshooting identifying form field


* [ ] Check profile

How is this diff from Vew profile?


* [ ] Anon user cannot edit, but can view.

not done; troubleshoot logging in as anon user

* [x] Other logged in users cannot edit, but can view.

done

* [x] ADDED: Login with username that has special characters

done

**Comment by treasuretron** [comment]
In GitLab by @Khiggins42 on Jul 12, 2018, 13:39

changed time estimate to 1h

**Comment by treasuretron** [comment]
In GitLab by @aspiringweb on Jul 12, 2018, 13:41

marked the task **Log in as a user we have recently created** as completed

**Comment by treasuretron** [comment]
In GitLab by @aspiringweb on Jul 12, 2018, 13:41

marked the task **View profile** as completed

**Comment by treasuretron** [comment]
In GitLab by @aspiringweb on Jul 12, 2018, 13:41

marked the task **Other logged in users cannot edit, but can view.** as completed

**Comment by treasuretron** [comment]
In GitLab by @aspiringweb on Jul 12, 2018, 13:41

changed the description

**Comment by treasuretron** [comment]
In GitLab by @aspiringweb on Jul 12, 2018, 13:42

changed the description

**Comment by treasuretron** [comment]
In GitLab by @aspiringweb on Jul 12, 2018, 13:43

@Khiggins42 I removed checked profile. You shouldn't have to log in as anon user, I think it should be as simple as given I goto /user/1/edit I should get 403. Let me know if you need help identifying or adding attributes to form fields.

**Comment by treasuretron** [comment]
In GitLab by @Khiggins42 on Jul 18, 2018, 15:25

mentioned in commit 89a0a3f21aef12cbf568bcd110fc3c2c3dc134af

**Comment by treasuretron** [comment]
In GitLab by @richbodo on Dec 11, 2018, 13:41

changed title from **Only a user can edit his own profile** to **Only a user can edit his own profile{+ - behat test+}**

**Comment by treasuretron** [comment]
In GitLab by @richbodo on Dec 11, 2018, 13:41

unassigned @Khiggins42
