### ISSUE TITLE
User can create an org and only that user can update their org - behat test

### ISSUE THREAD

**Issue by treasuretron** [spacebase/spacebasenz#99]
In GitLab by @richbodo on Apr 17, 2018, 20:20

* [x] Log in as a newly created user
* [x] Create a new organization
* [x] View the org
* [ ] Edit the org data
* [ ] That user can view the edited org data
* [ ] Anon and other logged in members can view but not edit the org data

**Comment by treasuretron** [comment]
In GitLab by @aspiringweb on Jul 12, 2018, 10:02

changed the description

**Comment by treasuretron** [comment]
In GitLab by @aspiringweb on Jul 12, 2018, 10:07

changed weight to **6**

**Comment by treasuretron** [comment]
In GitLab by @Khiggins42 on Jul 12, 2018, 13:22

* [ ] Log in as a newly created user

done

* [ ] Create a new organization

done

* [ ] View the org

done (Though with caveat that it’s viewing an existing org not the one created abovej. Adding a URL alias to orgs would prob solve this—as it is we don’t know what ID wil be at the end of the URL for the newly created org.)


* [ ] Edit the org data

not done; troubleshooting


* [ ] That user can view the edited org data

not done; troubleshooting


* [ ] Anon and other logged in members can view but not edit the org data

not done; troubleshooting

**Comment by treasuretron** [comment]
In GitLab by @Khiggins42 on Jul 12, 2018, 13:22

changed time estimate to 1h

**Comment by treasuretron** [comment]
In GitLab by @aspiringweb on Jul 12, 2018, 13:25

marked the task **Log in as a newly created user** as completed

**Comment by treasuretron** [comment]
In GitLab by @aspiringweb on Jul 12, 2018, 13:25

marked the task **Create a new organization** as completed

**Comment by treasuretron** [comment]
In GitLab by @aspiringweb on Jul 12, 2018, 13:25

marked the task **View the org** as completed

**Comment by treasuretron** [comment]
In GitLab by @aspiringweb on Jul 12, 2018, 13:26

@Khiggins42 ok let me know what issues you are having via the troubleshooting parts

**Comment by treasuretron** [comment]
In GitLab by @Khiggins42 on Jul 18, 2018, 15:25

mentioned in commit 89a0a3f21aef12cbf568bcd110fc3c2c3dc134af

**Comment by treasuretron** [comment]
In GitLab by @richbodo on Oct 23, 2018, 15:34

closed

**Comment by treasuretron** [comment]
In GitLab by @richbodo on Oct 23, 2018, 15:35

reopened

**Comment by treasuretron** [comment]
In GitLab by @richbodo on Dec 11, 2018, 13:43

changed title from **User can create an org and only that user can update their org** to **User can create an org and only that user can update their org{+ - behat test+}**

**Comment by treasuretron** [comment]
In GitLab by @richbodo on Dec 11, 2018, 13:43

unassigned @Khiggins42
